export enum ReportReason {
  Spoilers = 'spoilers',
  Language = 'language',
  Abusive = 'abusive',
  Spam = 'spam',
  Bigotry = 'bigotry',
  Political = 'political',
  OffTopic = 'offtopic',
  Support = 'support',
  Duplicate = 'duplicate',
  TooShort = 'too_short',
  Remove = 'remove',
  DataRefresh = 'data_refresh',
  Metadata = 'metadata',
  Adult = 'adult',
  Runtime = 'runtime',
  Tmdb = 'tmdb',
  Other = 'other',
}
