export enum SummaryDrawers {
  Sentiment = 'sentiment',
  Details = 'details',
  Cast = 'cast',
  Videos = 'videos',
  Trivia = 'trivia',
  Soundtrack = 'soundtrack',
  History = 'history',
  Social = 'social',
  WhereToWatch = 'where-to-watch',
  Seasons = 'seasons',
  Episode = 'episode',
  Notes = 'notes',
  Comments = 'comments',
  Review = 'review',
  Ratings = 'ratings',
  Rewatching = 'rewatching',
  Glance = 'glance',
}
