files:
  - source: /projects/client/i18n/meta/en.json
    translation: /projects/client/i18n/messages/%locale%.json
pull_request_title: 'feat(l10n): localization updates'
pull_request_assignees:
  - vladjerca
  - seferturan
commit_message: 'feat(l10n): update %original_file_name%'
append_commit_message: false
bundles:
  - 6
