export enum ConfirmationType {
  MarkAsWatched = 'mark-as-watched',
  RemoveFromWatched = 'remove-from-watched',
  RemoveFromHistory = 'remove-from-history',
  DropShow = 'drop-show',
  DropMovie = 'drop-movie',
  RestoreShow = 'restore-show',
  DeleteList = 'delete-list',
  RemoveFavorite = 'remove-favorite',
  RemoveFromWatchList = 'remove-from-watchlist',
  RemoveFromList = 'remove-from-list',
  UnfollowUser = 'unfollow-user',
  StopCheckin = 'stop-checkin',
  DeleteComment = 'delete-comment',
  SuppressRatingsToast = 'suppress-ratings-toast',
}
