export enum ConfirmationType {
  MarkAsWatched = 'mark-as-watched',
  RemoveFromWatched = 'remove-from-watched',
  RemoveFromHistory = 'remove-from-history',
  DropShow = 'drop-show',
  DropMovie = 'drop-movie',
  RestoreShow = 'restore-show',
  DeleteList = 'delete-list',
  RemoveFavorite = 'remove-favorite',
  RemoveFromWatchList = 'remove-from-watchlist',
  RemoveFromList = 'remove-from-list',
  UnfollowUser = 'unfollow-user',
  BlockUser = 'block-user',
  StopCheckin = 'stop-checkin',
  DeleteComment = 'delete-comment',
  SuppressRatingsToast = 'suppress-ratings-toast',
  Logout = 'logout',
  SimpleFilters = 'simple-filters',
  CancelVip = 'cancel-vip',
  CancelImport = 'cancel-import',
  CancelReset = 'cancel-reset',
  ClearWatchlist = 'clear-watchlist',
  HideRecommendation = 'hide-recommendation',
}
