import { z } from 'zod';

export const MediaReactionSchema = z.enum([
  'heart_eyes',
  'love',
  'rofl',
  'holding_back_tears',
  'partying',
  'mind_blown',
  'cursing',
  'weary',
  'woozy',
  'yawning',
  'spoiler',
  'shushing',
  'smiling_tear',
  'neutral',
  'shocked',
  'anxious',
  'thinking',
  'flushed',
  'melting',
  'grimacing',
  'vomiting',
  'eye_roll',
  'like',
  'rock_on',
  'dislike',
  'bravo',
  'skull',
  'popcorn',
  'fire',
  'crying',
  'pinched_fingers',
  'broken_heart',
  'freezing',
  'disguised',
  'nerd',
  'monocle',
]);

export type MediaReaction = z.infer<typeof MediaReactionSchema>;
