name: ℹ️ Ask a Question
description: Have a question? Shoot!
labels: ["question"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's [Code of Conduct](https://github.com/trakt/trakt-web/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
          
  - type: textarea
    attributes:
      label: Question
    validations:
      required: true
