export enum Region {
  NorthAmerica = 'north-america',
  Europe = 'europe',
  Asia = 'asia',
  MiddleEast = 'middle-east',
  Oceania = 'oceania',
  LatinAmerica = 'latin-america',
  Africa = 'africa',
}

export const COUNTRY_REGIONS: Readonly<Record<Region, ReadonlyArray<string>>> =
  {
    [Region.NorthAmerica]: ['us', 'ca'],
    [Region.Europe]: [
      'gb',
      'fr',
      'de',
      'it',
      'es',
      'dk',
      'ie',
      'se',
      'be',
      'ru',
      'no',
      'pl',
      'su',
      'nl',
      'at',
      'fi',
      'ro',
      'gr',
      'rs',
      'hu',
      'is',
      'yu',
      'xc',
      'ch',
      'bg',
      'cz',
      'ee',
      'ua',
    ],
    [Region.Asia]: ['in', 'jp', 'kr', 'hk', 'cn', 'th', 'tw', 'bd', 'id'],
    [Region.MiddleEast]: ['tr', 'ir', 'il', 'eg'],
    [Region.Oceania]: ['au', 'nz'],
    [Region.LatinAmerica]: ['mx', 'br', 'ar', 'cl', 'co'],
    [Region.Africa]: ['za'],
  };
