export enum FeatureFlag {
  SplitCast = 'split-cast',
  EditMode = 'edit-mode',
  ScopedFavorites = 'scoped-favorites',
  Rewatching = 'rewatching',
  Soundtrack = 'soundtrack',
  ListCounts = 'list-counts',
  GenrePicker = 'genre-picker',
  YouTubeSpecials = 'youtube-specials',
  TodayStory = 'today-story',
  YearInReview2026 = 'year-in-review-2026',
  LargeScreenCards = 'large-screen-cards',
  VipVeteran = 'vip-veteran',
  Reactions = 'reactions',
}
