import type { AnyReaction } from '$lib/requests/models/AnyReaction.ts';

export const EMOJI_BASE_URL = 'https://fonts.gstatic.com/s/e/notoemoji/latest';

// Source: https://googlefonts.github.io/noto-emoji-animation/
export const REACTIONS_CODE_MAP: Record<AnyReaction, string> = {
  like: '1f44d',
  dislike: '1f44e',
  love: '2764_fe0f',
  laugh: '1f602',
  shocked: '1f631',
  bravo: '1f44f',
  spoiler: '1fae3',
  heart_eyes: '1f60d',
  rofl: '1f923',
  holding_back_tears: '1f979',
  partying: '1f973',
  mind_blown: '1f92f',
  cursing: '1f92c',
  weary: '1f629',
  woozy: '1f974',
  yawning: '1f971',
  shushing: '1f92b',
  smiling_tear: '1f972',
  neutral: '1f610',
  anxious: '1f630',
  thinking: '1f914',
  flushed: '1f633',
  melting: '1fae0',
  grimacing: '1f62c',
  vomiting: '1f92e',
  eye_roll: '1f644',
  rock_on: '1f918',
  skull: '1f480',
  popcorn: '1f37f',
  fire: '1f525',
  crying: '1f62d',
  pinched_fingers: '1f90c',
  broken_heart: '1f494',
  freezing: '1f976',
  disguised: '1f978',
  nerd: '1f913',
  monocle: '1f9d0',
};

// FIXME: use translated keywords instead of English-only ones
export const REACTION_KEYWORDS: Record<AnyReaction, ReadonlyArray<string>> = {
  like: ['thumbs up', 'good', 'yes', 'approve', 'agree'],
  dislike: ['thumbs down', 'bad', 'no', 'meh', 'disagree'],
  love: ['heart', 'adore', 'romance', 'romantic'],
  laugh: ['lol', 'funny', 'haha', 'lmao', 'joke'],
  shocked: ['omg', 'scared', 'scary', 'scream', 'horror', 'wow', 'shock'],
  bravo: ['clap', 'applause', 'well done', 'great', 'impressive'],
  spoiler: ['peek', 'hide', 'reveal', 'spoilers'],
  heart_eyes: ['love', 'adore', 'crush', 'gorgeous', 'beautiful', 'omg'],
  rofl: ['lol', 'lmao', 'laugh', 'funny', 'hilarious', 'haha'],
  holding_back_tears: ['moved', 'touched', 'emotional', 'sad', 'aww', 'cry'],
  partying: ['party', 'celebrate', 'fun', 'hype', 'yay'],
  mind_blown: ['wow', 'omg', 'twist', 'shocking', 'amazing', 'genius'],
  cursing: ['angry', 'mad', 'rage', 'furious', 'swear', 'hate'],
  weary: ['tired', 'exhausted', 'ugh', 'frustrated'],
  woozy: ['dizzy', 'confused', 'drunk', 'weird', 'trippy'],
  yawning: ['bored', 'boring', 'sleepy', 'tired', 'slow', 'dull'],
  shushing: ['secret', 'quiet', 'hush', 'spoiler'],
  smiling_tear: ['bittersweet', 'sad', 'happy', 'nostalgic'],
  neutral: ['meh', 'ok', 'whatever', 'indifferent', 'fine'],
  anxious: ['nervous', 'tense', 'scared', 'scary', 'stress', 'suspense'],
  thinking: ['hmm', 'confused', 'curious', 'puzzling', 'think'],
  flushed: ['embarrassed', 'awkward', 'blush', 'cringe'],
  melting: ['cute', 'overwhelmed', 'swoon', 'aww'],
  grimacing: ['cringe', 'awkward', 'yikes', 'oops'],
  vomiting: ['gross', 'disgusting', 'sick', 'yuck', 'vomit'],
  eye_roll: ['annoyed', 'whatever', 'cliche', 'predictable'],
  rock_on: ['rock', 'metal', 'awesome', 'cool', 'epic'],
  skull: ['dead', 'dying', 'lol', 'lmao', 'hilarious'],
  popcorn: ['drama', 'entertaining', 'snack', 'binge'],
  fire: ['hot', 'lit', 'amazing', 'epic', 'banger'],
  crying: ['sad', 'tears', 'sob', 'heartbreaking', 'cry'],
  pinched_fingers: ['perfect', 'masterpiece', 'chef', 'kiss'],
  broken_heart: ['heartbroken', 'sad', 'breakup', 'devastating'],
  freezing: ['cold', 'chills', 'scary', 'frozen'],
  disguised: ['disguise', 'undercover', 'spy', 'incognito'],
  nerd: ['geek', 'smart', 'nerdy'],
  monocle: ['fancy', 'classy', 'curious', 'sophisticated'],
};
